// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class CustomerConfiguration
    : IEntityTypeConfiguration<Customer>
{
    public void Configure(
        EntityTypeBuilder<Customer> entity)
    {
        entity.ToTable("Customers", "crm");

        entity.HasIndex(
            e => e.LocationId,
            "IX_Customers_LocationId"
        );

        entity.HasIndex(
            e => e.CustomerCode,
            "UX_Customers_CustomerCode"
        ).IsUnique();

        entity.HasIndex(
            e => e.UserId,
            "UX_Customers_UserId"
        ).IsUnique();

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getutcdate())", "DF_Customers_CreateDate");
        entity.Property(e => e.CustomerCode)
            .HasMaxLength(50);
        entity.Property(e => e.CustomerName)
            .HasMaxLength(200);
        entity.Property(e => e.IsActive)
            .HasDefaultValue(true, "DF_Customers_IsActive");

        entity.HasOne(d => d.Location)
            .WithMany(
                p => p.Customers
            )
            
            .HasForeignKey(d => d.LocationId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Customers_Location");

        entity.HasOne(d => d.User)
            .WithOne(
                p => p.Customer
            )
            
            .HasForeignKey<Customer>(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Customers_User");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<Customer> entity);
}

