// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class LocationConfiguration
    : IEntityTypeConfiguration<Location>
{
    public void Configure(
        EntityTypeBuilder<Location> entity)
    {
        entity.ToTable("Locations", "crm");

        entity.HasIndex(
            e => e.ParentLocationId,
            "IX_Locations_ParentLocationId"
        );

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getutcdate())", "DF_Locations_CreateDate");
        entity.Property(e => e.IsActive)
            .HasDefaultValue(true, "DF_Locations_IsActive");
        entity.Property(e => e.Name)
            .HasMaxLength(150);

        entity.HasOne(d => d.ParentLocation)
            .WithMany(
                p => p.InverseParentLocation
            )
            
            .HasForeignKey(d => d.ParentLocationId)
            .HasConstraintName("FK_Locations_Parent");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<Location> entity);
}

