// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class PermissionConfiguration
    : IEntityTypeConfiguration<Permission>
{
    public void Configure(
        EntityTypeBuilder<Permission> entity)
    {
        entity.ToTable("Permissions", "auth");

        entity.HasIndex(
            e => e.Name,
            "UQ_Permissions_Name"
        ).IsUnique();

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())", "DF_Permissions_CreateDate");
        entity.Property(e => e.Description)
            .HasMaxLength(250);
        entity.Property(e => e.Name)
            .HasMaxLength(150);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<Permission> entity);
}

