// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class RoleConfiguration
    : IEntityTypeConfiguration<Role>
{
    public void Configure(
        EntityTypeBuilder<Role> entity)
    {
        entity.ToTable("Roles", "auth");

        entity.HasIndex(
            e => e.Name,
            "UQ_Roles_Name"
        ).IsUnique();

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())", "DF_Roles_CreateDate");
        entity.Property(e => e.Description)
            .HasMaxLength(250);
        entity.Property(e => e.Name)
            .HasMaxLength(100);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<Role> entity);
}

