// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class RolePermissionConfiguration
    : IEntityTypeConfiguration<RolePermission>
{
    public void Configure(
        EntityTypeBuilder<RolePermission> entity)
    {
        entity.HasKey(
            e => new { e.RoleId, e.PermissionId }
        );

        entity.ToTable("RolePermissions", "auth");

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())", "DF_RolePermissions_CreateDate");

        entity.HasOne(d => d.Permission)
            .WithMany(
                p => p.RolePermissions
            )
            
            .HasForeignKey(d => d.PermissionId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RolePermissions_Permissions");

        entity.HasOne(d => d.Role)
            .WithMany(
                p => p.RolePermissions
            )
            
            .HasForeignKey(d => d.RoleId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RolePermissions_Roles");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<RolePermission> entity);
}

