// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class UserRoleConfiguration
    : IEntityTypeConfiguration<UserRole>
{
    public void Configure(
        EntityTypeBuilder<UserRole> entity)
    {
        entity.HasKey(
            e => new { e.UserId, e.RoleId }
        );

        entity.ToTable("UserRoles", "auth");

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())", "DF_UserRoles_CreateDate");

        entity.HasOne(d => d.Role)
            .WithMany(
                p => p.UserRoles
            )
            
            .HasForeignKey(d => d.RoleId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UserRoles_Roles");

        entity.HasOne(d => d.User)
            .WithMany(
                p => p.UserRoles
            )
            
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UserRoles_Users");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<UserRole> entity);
}

