// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Crm.Infrastructure.Persistence.Configurations;

public partial class UserConfiguration
    : IEntityTypeConfiguration<User>
{
    public void Configure(
        EntityTypeBuilder<User> entity)
    {
        entity.ToTable("Users", "auth");

        entity.HasIndex(
            e => e.UserName,
            "UQ_Users_UserName"
        ).IsUnique();

        entity.Property(e => e.CreateDate)
            .HasDefaultValueSql("(getdate())", "DF_Users_CreateDate");
        entity.Property(e => e.LastName)
            .HasMaxLength(150);
        entity.Property(e => e.Name)
            .HasMaxLength(50);
        entity.Property(e => e.PasswordHash)
            .HasMaxLength(255);
        entity.Property(e => e.Phone)
            .HasMaxLength(15);
        entity.Property(e => e.UserName)
            .HasMaxLength(50);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(
        EntityTypeBuilder<User> entity);
}

