// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities.BaseEntites;



namespace Crm.Domain.Entities;


public partial class Customer : BaseEntity<long>
{

    public long UserId { get; set; }


    public long LocationId { get; set; }


    public string CustomerCode { get; set; } = null!;


    public string CustomerName { get; set; } = null!;


    public bool IsActive { get; set; }


    public int? PurchasePerformanceScore { get; set; }


    public int? PurchaseMixQualityScore { get; set; }


    public int? StoreCapacityScore { get; set; }


    public int? LoyaltyStrategicCooperationScore { get; set; }


    public int? ProfessionalStaffQualityScore { get; set; }


    public int? RegionalMarketPotentialScore { get; set; }

    public virtual Location Location { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}

