// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities.BaseEntites;



namespace Crm.Domain.Entities;


public partial class Location : BaseEntity<long>
{

    public long? ParentLocationId { get; set; }


    public string Name { get; set; } = null!;


    public bool IsActive { get; set; }

    public virtual ICollection<Customer>
        Customers { get; set; }
        = new List<Customer>();

    public virtual ICollection<Location>
        InverseParentLocation { get; set; }
        = new List<Location>();

    public virtual Location? ParentLocation { get; set; }
}

