// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;



namespace Crm.Domain.Entities;


public partial class RolePermission
{

    public long RoleId { get; set; }


    public long PermissionId { get; set; }


    public DateTime CreateDate { get; set; }

    public virtual Permission Permission { get; set; } = null!;

    public virtual Role Role { get; set; } = null!;
}

