// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities.BaseEntites;



namespace Crm.Domain.Entities;


public partial class Role : BaseEntity<long>
{

    public string Name { get; set; } = null!;


    public string? Description { get; set; }

    public virtual ICollection<RolePermission>
        RolePermissions { get; set; }
        = new List<RolePermission>();

    public virtual ICollection<UserRole>
        UserRoles { get; set; }
        = new List<UserRole>();
}

