// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities.BaseEntites;



namespace Crm.Domain.Entities;


public partial class User : BaseEntity<long>
{

    public string? Name { get; set; }


    public string? LastName { get; set; }


    public string UserName { get; set; } = null!;


    public string PasswordHash { get; set; } = null!;


    public string Phone { get; set; } = null!;


    public bool IsSuperAdmin { get; set; }

    public virtual ICollection<UserRole>
        UserRoles { get; set; }
        = new List<UserRole>();
}

