// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;



namespace Crm.Domain.Entities;


public partial class UserRole
{

    public long UserId { get; set; }


    public long RoleId { get; set; }


    public DateTime CreateDate { get; set; }

    public virtual Role Role { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}

