// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Crm.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Crm.Infrastructure.Persistence;

public partial class CrmDbContext : DbContext
{
    public CrmDbContext(
        DbContextOptions<CrmDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer>
        Customers { get; set; }

    public virtual DbSet<Location>
        Locations { get; set; }

    public virtual DbSet<Permission>
        Permissions { get; set; }

    public virtual DbSet<Role>
        Roles { get; set; }

    public virtual DbSet<RolePermission>
        RolePermissions { get; set; }

    public virtual DbSet<User>
        Users { get; set; }

    public virtual DbSet<UserRole>
        UserRoles { get; set; }

    protected override void OnModelCreating(
        ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(
            typeof(CrmDbContext).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(
        ModelBuilder modelBuilder);
}

